#!/usr/bin/env bash
#
# Torque - minimal tui for transmission-daemon.

clear_screen() {
    printf '\e[?7l\e[?25l\e[2J\e[;H'
}

get_term_size() {
    shopt -s checkwinsize; (:;:)
    [[ -z "$LINES" ]] && read -r LINES COLUMNS < <(stty size)
    ((j=(LINES-2)/3))
}

status() {
    printf '\e[2m\e[%s;H%s\e[m' "$((LINES-1))" "$1"
}

get_torrents() {
    IFS=$'\n' read -d "" -ra t < <(transmission-remote -l)
    unset 't[0]' 't[-1]' 2>/dev/null

    t=("${t[@]//[0-9][0-9] [a-z][a-z][a-z]/.}")
    t=("${t[@]//[0-9] [a-z][a-z][a-z]?/.}")
    t=("${t[@]//Up & Down/Downloading}")
    t=("${t[@]//     None/0 MB}")
    t=("${t[@]//None/0.0}")
    t=("${t[@]//n\/a/0%}")

    for((i=${k:=0};i<(j=j>${#t[@]}?${#t[@]}:j);i++));{ t_print "${t[$i]}";}
    status "[s]tart [p]ause [r]emove [o]pen [j/k] scroll ($j/${#t[@]})"$'\e[;H'
}

t_print() {
    IFS=" %" read -r num perc have unit fin up down _ stat name <<< "$1"

    [[ "$fin" == *Done* ]] && local c=$'\e[33m✓ '
    ((size=perc!=0?${have/.*}*100/perc:0))

    printf '\e[K\e[2m%s\e[m \e[1m%s%s\e[m\n' \
           "$num:" "${c:-$'\e[31m'}" "$name"
    printf '\e[K%s\e[99D\e[17C%s\e[99D\e[36C%s\e[99D\e[47C%s\n\e[K\n' \
           "   $stat: " "$have / $size $unit" "⇣ $down" "⇡ $up"
}

prompt() {
    torrent() { transmission-remote "$@" >/dev/null; }
    status $'\e[B\e[?25h'

    case "$1" in
        s) read -rp "start torrent: #";  torrent -t "$REPLY" -s ;;
        p) read -rp "pause torrent: #";  torrent -t "$REPLY" -S ;;
        r) read -rp "remove torrent: #"; torrent -t "$REPLY" -r; k=0 ;;
        o) read -rp "load magnet: "; torrent -a "$REPLY"; k=0 ;;
        j) ((j==${#t[@]}))||((k=k>=j?k:++k,j=j<${#t[@]}?++j:j)) ;;
        k) ((k==0))||((k=k<=j?k>0?--k:0:j,j=j>0?--j:j)) ;;
    esac

    [[ "$1" =~ (j|k) ]] || clear_screen && printf '\e[?25l\e[;H'
}

main() {
    clear_screen
    get_term_size; printf '\e[0;%sr\e[?19l' "$((j*3+1))"

    trap $'printf \e[r\e[?19h\e[?25h\e[?7h\e[999B' EXIT
    trap  'clear_screen; get_term_size; k=0' SIGWINCH

    for ((;;)); { get_torrents; read -rsN1 -t1 && prompt "$REPLY"; }
}

main "$@"
